### ISSUE TITLE
Cannot get rid of "Feuil1" sheet in the rgv exported Excel workbook

### ISSUE THREAD

**Issue by Biopticon** [davidgohel/rvg#41] opened 2021-02-23 22:20 UTC
In your example of using rgv to export a graph to Excel, I cannot change the sheet name "Feuil1" to any other. If I use doc <- add_sheet(doc, label = "Sheet1") to add a new sheet to export my graph into, there still will be a sheet called "Feuil1" in the workbook! How can I have just a sheet I named in the workbook, without "Feuil1? 

Also, if the file Excel file I am going to export a graph, is open, the code below crashes.  Is there any way to peacefully exit?

Thank you.

doc <- read_xlsx()
doc <- xl_add_vg(doc, sheet = "Feuil1", code = print(gg),  width = 6, height = 6, left = 1, top = 2 )
print(doc, target = "vg.xlsx")

**Comment by davidgohel** [comment] 2021-02-24 09:54
I believe it's a duplicate of https://github.com/davidgohel/officer/issues/356

**Closed by davidgohel** 2021-02-24 09:54 UTC
Labels: duplicate

**Comment by Biopticon** [comment] 2021-02-24 18:52
Thank you, David. We are all eager to know when and if you come up with complete R packages for exporting plots in editable formats in docx, xlsx, and pptx; an enormous task!

**Comment by davidgohel** [comment] 2021-02-24 19:03
* docx: it's not possible, text can't be sized or positioned as expected. The function is no more existing (since years).
* pptx: it's working 
* xlsx: it's working. The officer API on xlsx is minimum as openxlsx do very well this job (for example `openxlsx::removeWorksheet()`).
